AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda Functions from 6998 HW2.
Resources:
  6998hw2LF1:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 6998_hw2_LF1.lambda_handler
      Runtime: python3.8
      CodeUri: ./lambda_functions
      Description: ''
      MemorySize: 128
      Timeout: 10
  6998hw2LF2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 6998_hw2_LF2.lambda_handler
      Runtime: python3.8
      CodeUri: ./lambda_functions
      Description: ''
      MemorySize: 128
      Timeout: 10
