AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda Functions from 6998 HW2.
Resources:
  6998hw2LF1:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./lambda_functions
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::252052963271:role/service-role/6998_hw2_LF1-role-74hgm5u6'